-- Pulse music app schema
-- Run this in the Supabase SQL editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.tracks (
  id bigint generated by default as identity primary key,
  title text not null,
  artist text not null,
  album text,
  duration_seconds integer not null default 0,
  cover_url text,
  audio_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.playlists (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  description text,
  cover_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.playlist_tracks (
  playlist_id bigint not null references public.playlists(id) on delete cascade,
  track_id bigint not null references public.tracks(id) on delete cascade,
  position integer not null default 0,
  primary key (playlist_id, track_id)
);

create table if not exists public.likes (
  user_id uuid not null references auth.users(id) on delete cascade,
  track_id bigint not null references public.tracks(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, track_id)
);

create index if not exists tracks_title_idx on public.tracks using gin (to_tsvector('english', title || ' ' || artist));
create index if not exists playlists_user_idx on public.playlists(user_id);

alter table public.profiles enable row level security;
alter table public.tracks enable row level security;
alter table public.playlists enable row level security;
alter table public.playlist_tracks enable row level security;
alter table public.likes enable row level security;

create policy "profiles are public" on public.profiles for select using (true);
create policy "users manage own profile" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "tracks are public" on public.tracks for select using (true);
create policy "users read own playlists" on public.playlists for select using (auth.uid() = user_id);
create policy "users create own playlists" on public.playlists for insert with check (auth.uid() = user_id);
create policy "users update own playlists" on public.playlists for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users delete own playlists" on public.playlists for delete using (auth.uid() = user_id);
create policy "playlist tracks visible to playlist owner" on public.playlist_tracks for select using (exists (select 1 from public.playlists p where p.id = playlist_id and p.user_id = auth.uid()));
create policy "playlist owner manages tracks" on public.playlist_tracks for all using (exists (select 1 from public.playlists p where p.id = playlist_id and p.user_id = auth.uid())) with check (exists (select 1 from public.playlists p where p.id = playlist_id and p.user_id = auth.uid()));
create policy "users read own likes" on public.likes for select using (auth.uid() = user_id);
create policy "users create own likes" on public.likes for insert with check (auth.uid() = user_id);
create policy "users delete own likes" on public.likes for delete using (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, display_name) values (new.id, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1))) on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

insert into public.tracks (title, artist, album, duration_seconds, cover_url, audio_url)
select * from (values
 ('Midnight Drive', 'Nova Lane', 'Midnight Drive', 222, null, null),
 ('Neon Skies', 'The Satellites', 'Neon Skies', 248, null, null),
 ('Golden Hour', 'Mira Sol', 'Golden Hour', 206, null, null),
 ('Afterglow', 'Kairo', 'Afterglow', 231, null, null),
 ('City Lights', 'Atlas Youth', 'City Lights', 255, null, null)
) as seed(title, artist, album, duration_seconds, cover_url, audio_url)
where not exists (select 1 from public.tracks);
